runtime: nodejs10
service: ayana-admin

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: "production"
  REACT_APP_BUILD_ENV: "production"
  PORT: 8080

handlers:
  - url: /.*
    secure: never
    redirect_http_response_code: 301
    script: auto
